apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-cart-service
  template:
    metadata:
      labels:
        app: shopping-cart-service
    spec:
      containers:
        - name: shopping-cart-service
          image: eydersantiago/shopping-cart-service:v9
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-cart-service
spec:
  selector:
    app: shopping-cart-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP










































# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: shopping-cart-service
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: shopping-cart-service
#   template:
#     metadata:
#       labels:
#         app: shopping-cart-service
#     spec:
#       containers:
#         - name: shopping-cart-service
#           image: eydersantiago/shopping-cart-service:v9 # Actualiza con tu imagen de Docker
#           ports:
#             - containerPort: 3000
#           env:
#             - name: PAYMENT_SERVICE_URL
#               value: "http://payment-service"
#             # - name: ERROR_PAGES_URL
#             #   value: "http://error-pages:8080"
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: shopping-cart-service
# spec:
#   selector:
#     app: shopping-cart-service
#   ports:
#     - protocol: TCP
#       port: 3000
#       targetPort: 3000
      
